# Use a base image with a minimal Linux distribution
FROM ubuntu:latest

# ---------------------------------------------------------------------------------------
# TASKs:   
    # add django to it aswell send image generated by the 
# ---------------------------------------------------------------------------------------

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y wget && \
    rm -rf /var/lib/apt/lists/*

# Download and install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
    bash miniconda.sh -b -p /opt/conda && \
    rm miniconda.sh

# Add Miniconda to PATH
ENV PATH=/opt/conda/bin:$PATH

# Verify installation
RUN conda info --all
RUN pip install prophet --pre
RUN pip install plotly

# to update & upgrade all packages
RUN apt update && apt upgrade -y
# Set default command to run when the container starts

# folder for prophet prediction files
RUN mkdir model
WORKDIR /model
COPY . /model/

RUN 


CMD ["bash"]
